# Generated by Django 5.2.11 on 2026-02-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade_point',
            field=models.CharField(choices=[('10', 'A (10)'), ('9', 'A- (9)'), ('8', 'B (8)'), ('7', 'B- (7)'), ('6', 'C (6)'), ('5', 'C- (5)'), ('4', 'D (4)'), ('2', 'E (2)'), ('0', 'NC (0)')], max_length=2),
        ),
    ]
